version: '2'


services:
  web:
    build: .
    command: bash runserver.sh
    volumes:
      - .:/code
    ports:
      - "8999:8000"

    links:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=composetest
      - MYSQL_PASSWORD=testpassword
      - MYSQL_DATABASE=composetest
    volumes:
    - census-db-data-new:/var/lib/mysql

volumes:
  census-db-data-new:
