# Generated by Django 2.0.9 on 2021-04-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0035_auto_20200611_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecopy',
            name='Height',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basecopy',
            name='Width',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
